### PR TITLE
fix(NotificationCenter): lock order inversion deadlock #5159

### LINKED ISSUE #5159: Lock-order-inversion deadlock in NotificationCenter
#### Summary

`NotificationCenter` methods call observer methods (`start()`, `disable()`) while holding the internal mutex, creating a lock-order-inversion with Observer's mutex.

#### Deadlock Scenario

**Thread A** (eg. `SocketRreactor::run()`):
1. `Observer::notify()` holds Observer mutex (M0)
2. Handler calls `removeEventHandler()` ([documented as safe](https://github.com/pocoproject/poco/blob/17864c39a8d9bf9c7ecb924f90d61f3e56a1f918/Net/include/Poco/Net/SocketReactor.h#L116-L118))
3. → `hasObserver()` waits for NotificationCenter mutex (M1)

**Thread B** (shutdown):
1. `removeObserver()` holds NotificationCenter mutex (M1)
2. → `disable()` waits for Observer mutex (M0)

**Result:** Deadlock (M0 → M1, M1 → M0)

#### Affected Methods

- `addObserver()` - calls `start()` under lock
- `removeObserver()` - calls `disable()` under lock
- `clear()` - calls `disable()` under lock

#### Fix

Release lock before calling observer methods:

```cpp
void NotificationCenter::addObserver(const AbstractObserver& observer)
{
	AbstractObserverPtr pObserver = observer.clone();
	{
		RWLock::ScopedWriteLock lock(_mutex);
		_observers.push_back(pObserver);
	}
	// Start outside the lock to avoid deadlock with Observer mutex
	pObserver->start();
}
```

### PR DESCRIPTION
**Pull request by aleks-f**
# Branch Summary: 5159-nc-deadlock

This branch fixes several thread-safety issues and deadlocks reported in issues #5159, #5161, and #5162.

Closes #5159, #5161, and #5162.

## Issues Addressed

- **#5159**: NotificationCenter lock order inversion deadlock
- **#5161**: PollSet and Pipe thread-safety issues (data races detected by TSan)
- **#5162**: General thread synchronization improvements

### IOLock (`Foundation/include/Poco/IOLock.h`, `Foundation/src/IOLock.cpp`)

A new lock-free synchronization primitive for coordinating I/O operations with close/shutdown:

- `IOLock` - tracks whether an I/O operation is in progress and whether close has been requested
- `ScopedIOLock` - RAII wrapper that enters on construction and leaves on destruction
- Uses `std::atomic<bool>` for `_closed` and `_inProgress` flags
- Provides `markClosed()`, `wait()`, `tryWait()`, and `close()` methods

### ScopedSocketReactor (`Net/include/Poco/Net/SocketReactor.h`)

A new RAII wrapper utility class that starts a SocketReactor in a background thread and automatically stops/joins on destruction:

```cpp
ScopedSocketReactor reactor;
reactor->addEventHandler(socket, observer);
// reactor runs in background thread
// automatically stopped and joined when reactor goes out of scope
```

### NotificationCenter (#5159)
- Fixed lock order inversion deadlock in observer notification

### Pipe (#5161)
- Added `IOLock` synchronization for thread-safe read/write operations
- Fixed close ordering: **write end must be closed before read end** to send EOF to blocked readers
- Fixed race condition: `wait()` for I/O completion now happens **before** closing file descriptors
- Affects both POSIX and Windows implementations

### PollSet (#5161)
- Added `IOLock` to coordinate `poll()` with destructor
- Prevents use-after-free when `poll()` is running during destruction
- Exit early on poll error when closed
- Affects epoll, poll, and select implementations

### New Tests
- `PipeTest` - comprehensive test suite including `testCloseRace` for concurrent close/read
- `testConcurrentHandlerRemoval` in SocketReactorTest - tests concurrent handler removal

### CI Enhancements
- Added sanitized builds (ASan, TSan, UBSan) to CI workflow

## Files Changed

| Component | Files |
|-----------|-------|
| IOLock | `IOLock.h`, `IOLock.cpp` (new) |
| Pipe | `PipeImpl_POSIX.h/cpp`, `PipeImpl_WIN32.h/cpp`, `Pipe.cpp` |
| PollSet | `PollSet.cpp` |
| SocketReactor | `SocketReactor.h`, `SocketReactor.cpp` |
| Tests | `PipeTest.cpp/h`, `SocketReactorTest.cpp/h`, `NotificationCenterTest.cpp/h` |
| CI | `.github/workflows/ci.yml` |

### Pipe Close Sequence (Before)
```cpp
void PipeImpl::closeRead() {
    if (_readfd != -1) close(fd);      // Race: close while read() in progress
}
```

### Pipe Close Sequence (After)
```cpp
void PipeImpl::closeRead() {
    _readLock.markClosed();
    _readLock.wait();              // Wait for any in-progress read to finish
    int fd = _readfd.exchange(-1);
    if (fd != -1) close(fd);       // Now safe to close
}
```

### Destructor Close Order (Before)
```cpp
~PipeImpl() {
    closeRead();   // Wrong: blocks readers waiting for data
    closeWrite();
}
```

### Destructor Close Order (After)
```cpp
~PipeImpl() {
    closeWrite();  // Correct: sends EOF to unblock readers
    closeRead();
}
```

### CODE REVIEW

File: Foundation/include/Poco/IOLock.h [hunk 1]
```diff
@@ -0,0 +1,200 @@
+//
+// IOLock.h
+//
+// Library: Foundation
+// Package: Threading
+// Module:  IOLock
+//
+// Definition of the IOLock class.
+//
+// Copyright (c) 2004-2008, Applied Informatics Software Engineering GmbH.,
```
Comment (matejk) [inline Foundation/include/Poco/IOLock.h]: Wrong  (C) year. Blast from the past! :)

File: Foundation/src/NotificationCenter.cpp [hunk 2]
```diff
@@ -38,24 +38,34 @@ NotificationCenter::~NotificationCenter()
 
 void NotificationCenter::addObserver(const AbstractObserver& observer)
 {
-	RWLock::ScopedWriteLock lock(_mutex);
-	_observers.emplace_back(observer.clone());
-	_observers.back()->start();
+	AbstractObserverPtr pObserver = observer.clone();
```
Comment (matejk) [inline Foundation/src/NotificationCenter.cpp:41]: Why does the observer have to be cloned before lock?

File: Foundation/include/Poco/IOLock.h [hunk 3]
```diff
@@ -0,0 +1,200 @@
...
+
+
+#include "Poco/Foundation.h"
+#include <atomic>
+
+
+namespace Poco {
+
+
+class Foundation_API IOLock
```
Comment (matejk) [inline Foundation/include/Poco/IOLock.h:29]: Perhaps `IOResourcePin` or `IOResourceHold` to distinguish from mutex-like locking?

**Review by matejk — COMMENTED** [review]
Some comments in the code. In addition: Would IOLock also deserve its own unit tests?

File: Foundation/src/IOLock.cpp [hunk 4]
```diff
@@ -0,0 +1,69 @@
...
+void IOLock::markClosed()
+{
+	_closed.store(true);
+}
+
+
+void IOLock::wait()
+{
+	while (_inProgress.load())
+		std::this_thread::sleep_for(std::chrono::microseconds(10));
```
Comment (matejk) [inline Foundation/src/IOLock.cpp:70]: Use std::condition_variable instead of busy loop?

File: Foundation/src/IOLock.cpp [hunk 5]
```diff
@@ -0,0 +1,69 @@
...
+#include <chrono>
+#include <thread>
+
+
+namespace Poco {
+
+
+bool IOLock::enter()
+{
+	_inProgress.store(true);
```
Comment (matejk) [inline Foundation/src/IOLock.cpp:26]: Would it make sense to add detection if the second thread called enter()? debug assertion or exception?

Comment (aleks-f) [reply Foundation/src/IOLock.cpp:26]: IOLock explicitly does not support multi-threaded I/O. It can be done, but I don't think the complications it brings are worth it, the class does one thing only - syncing between destruction in one thread and I/O in another. Whoever is doing l/O from multiple threads, I wish him good luck.

EDIT: to be more specific, whoever is doing I/O on a single channel, or polls, from multiple threads

File: Foundation/src/IOLock.cpp (hunk 4 above)
Comment (aleks-f) [reply Foundation/src/IOLock.cpp:70]: 2ec60b0c1
let's see how that does in ci ...

File: Foundation/src/NotificationCenter.cpp (hunk 2 above)
Comment (aleks-f) [reply Foundation/src/NotificationCenter.cpp:41]: because this is precisely where the deadlock potential resides:
```cpp
pObserver->start();
```

File: Foundation/src/IOLock.cpp (hunk 5 above)
Comment (matejk) [reply Foundation/src/IOLock.cpp:26]: What I meant was to detect multiple threads using IOLock and prevent that (or log or throw and exception).

Comment (aleks-f) [reply Foundation/src/IOLock.cpp:26]: I guess one thing that could be done is to keep thread references and add some sanity checks, but I would do it for debug build only and I really don't have time to do it. As far as I'm concerned, we made a knife, if someone gets cut, thats' on them.

**Comment by matejk** [comment]
@aleks-f , ready to merge?
