### PR TITLE
enh(Poco::ActiveThreadPool): make it easy to use correctly

### LINKED ISSUE #4544: The load balancing issue in Poco::ActiveThreadPool
**Describe the bug**
Each thread in `Poco::ActiveThreadPool` has its own `Poco::NotificationQueue`.
If I have 2 types of Runnable like this:
```cpp
class LongTimeTask : public Poco::Runnable {
    void run() {
        sleep(2 * 60 * 1000);
    }
};

class ShortTimeTask : public Poco::Runnable {
    void run() {
        sleep(1);
    }
};

int capacity = 2;
Poco::ActiveThreadPool pool(capacity);

for (int i = 0; i < 10; i++) {
    pool.start(new LongTimeTask); // [BUG!!!] all long time task will enqueue to thread#1
    pool.start(new ShortTimeTask); // [BUG!!!] all short time task will enqueue to thread#2
}
```

### LINKED ISSUE #4634: Poco::ActiveThreadPool _targetCompleted event never reset
If a thread in the pool finised its **first task**, than it will call `_targetCompleted.set()`,
And than the thead will continue to run its **second task** without calling `_targetCompleted.reset()`.

If I call the `Poco::ActiveThreadPool::join()` function now, it returns immediately, even though there are still many tasks in the queue that haven't been completed.

https://github.com/pocoproject/poco/blob/1eebd46c0487356fc3c89991ddc160ab97a6f001/Foundation/src/ActiveThreadPool.cpp#L192

### PR DESCRIPTION
**Pull request by siren186**
1. Fixed #4544
2. Fixed #4634
3. Support dynamic manages and recycles individual `Poco::Thread` objects.
4. Support priority queue tasks

### CODE REVIEW

File: Foundation/src/ActiveThreadPool.cpp [hunk 1]
```diff
@@ -15,347 +15,493 @@
...
+		return _firstIndex > _lastIndex;
 	}
 
-	const std::string &threadName() const
+	void push(Runnable& runnable)
 	{
-		return _name;
+		poco_assert(!isFull());
+		_lastIndex += 1;
+		_entries[_lastIndex] = &runnable;
```
[the remark this answers is not in the document]
Comment (matejk) [reply Foundation/src/ActiveThreadPool.cpp:55]: @siren186 , can you take a look at this warning?

File: Foundation/src/ActiveThreadPool.cpp [hunk 2]
```diff
@@ -15,347 +15,493 @@
...
-	_needToStop = false;
 	_thread.start(*this);
 }
 
 
-void ActiveThread::start(Thread::Priority priority, Runnable& target)
+void ActivePooledThread::setRunnable(Runnable& target)
 {
-	_pTargetQueue.enqueueNotification(Poco::makeAuto<NewActionNotification>(priority, target, _name));
+	_pTarget = &target;
```
[the remark this answers is not in the document]
Comment (matejk) [reply Foundation/src/ActiveThreadPool.cpp:177]: @siren186 , can you take a look at this warning?

**Comment by matejk** [comment]
@siren186 , can you write a test that verifies the changes?

File: Foundation/src/ActiveThreadPool.cpp [hunk 3]
```diff
@@ -15,347 +15,493 @@
...
 namespace Poco {
 
-class NewActionNotification: public Notification
+class QueuePage
 {
 public:
-	using Ptr = AutoPtr<NewActionNotification>;
+	enum
+	{
+		MaxPageSize = 256
```
Comment (matejk) [inline Foundation/src/ActiveThreadPool.cpp:32]: Use constexpr here?

OTOH: Why is this restriction necessary?

File: Foundation/src/ActiveThreadPool.cpp [hunk 4]
```diff
@@ -15,347 +15,493 @@
...
 	}
 
 private:
-	std::atomic<Thread::Priority> _priority;
-	Runnable& _runnable;
-	std::string _name;
+	int _priority = 0;
+	int _firstIndex = 0;
+	int _lastIndex = -1;
+	Runnable* _entries[MaxPageSize];
```
Comment (matejk) [inline Foundation/src/ActiveThreadPool.cpp:99]: Why not use one of the standard containers instead of implementing own?

File: Foundation/src/ActiveThreadPool.cpp [hunk 5]
```diff
@@ -15,347 +15,493 @@
...
+
+	int activeThreadCount() const;
+
+public:
+	mutable FastMutex mutex;
+	std::string name;
+	std::set<ActivePooledThread*> allThreads;
+	std::list<ActivePooledThread*> waitingThreads;
+	std::list<ActivePooledThread*> expiredThreads;
+	std::list<QueuePage*> runnables;
```
Comment (matejk) [inline Foundation/src/ActiveThreadPool.cpp:146]: Would it be possible to use unique_ptr instead of bare pointers?

File: Foundation/src/ActiveThreadPool.cpp [hunk 6]
```diff
@@ -15,347 +15,493 @@
...
+	auto it = std::upper_bound(runnables.begin(), runnables.end(), priority, comparePriority);
+	runnables.insert(it, new QueuePage(target, priority));
 }
 
 
-void ActiveThreadPool::startWithPriority(Thread::Priority priority, Runnable& target)
+int ActiveThreadPoolPrivate::activeThreadCount() const
 {
-	getThread()->start(priority, target);
+	return (int)(allThreads.size() - expiredThreads.size() - waitingThreads.size());
```
Comment (matejk) [inline Foundation/src/ActiveThreadPool.cpp:369]: Change return type to std::size_t to avoid type casting or use C++ instead of C casting.

File: Foundation/include/Poco/ActiveThreadPool.h [hunk 7]
```diff
@@ -107,38 +83,14 @@ class Foundation_API ActiveThreadPool
...
-
-	std::string _name;
-	int _capacity;
-	int _serial;
-	int _stackSize;
-	ThreadVec _threads;
-	mutable FastMutex _mutex;
-	std::atomic<size_t> _lastThreadIndex{0};
+private:
+	ActiveThreadPoolPrivate* m_impl;
```
Comment (matejk) [inline Foundation/include/Poco/ActiveThreadPool.h:91]: Use unique_ptr

File: Foundation/src/ActiveThreadPool.cpp (hunk 2 above)
[the remark this answers is not in the document]
Comment (siren186) [reply Foundation/src/ActiveThreadPool.cpp:177]: That is because I tried to assign `Runnable& target` to `Runnable* _pTarget`.
I used the same code as `Poco::ThreadPool`:
https://github.com/pocoproject/poco/blob/e4aaeacea8872e9361f3d67217c5a254cf6fc773/Foundation/src/ThreadPool.cpp#L89

I do not known how to fix this warning.

**Comment by matejk** [comment]
@siren186, Thank you for updating the code. Some compile and testrun actions fail.

File: Foundation/src/ActiveThreadPool.cpp (hunk 2 above)
[the remark this answers is not in the document]
Comment (siren186) [reply Foundation/src/ActiveThreadPool.cpp:197]: This warning can be fixed by `std::optional<std::reference_wrapper<Runnable>> _pTarget`.
But unfortunately it cannot be compiled by macOS.
see: https://github.com/pocoproject/poco/issues/4650

**Comment by matejk** [comment]
@siren186 , I found out that increasing the macOS target version is better than not using optional. Two changes are committed to a related branch in Poco repository.

Would you merge those two commits?

**Comment by siren186** [comment]
@matejk commits are merged.
I'm not working on macOS, so that I don't know how to increase the macOS target version.

**Comment by siren186** [comment]
@matejk Is this check action error caused by my PR ?
https://github.com/pocoproject/poco/actions/runs/10556219311/job/29241333775

**Comment by matejk** [comment]
I don't think so. I started the job again.

**Comment by bas524** [comment]
@siren186 , @matejk 
Sorry for the long silence.
I've checked this changes. 
In my PR #4548 you can see two tests:
* FifoEventTest::testAsyncNotifyBenchmark
* ActiveThreadPoolTest::testActiveThreadLoadBalancing

First test verifies that we can run more async events than threads in the pool. My test returns OK in booth realisations, but my realisation is 2 times faster
this PR
```shell
./Foundation-testrunner testAsyncNotifyBenchmark

testAsyncNotifyBenchmark: Total async events is 10000000
total wait time is 107072ms (avg notify-time per run is 107.072ms)

OK (1 tests)
```

my PR
```shell
./Foundation-testrunner testAsyncNotifyBenchmark

testAsyncNotifyBenchmark: Total async events is 10000000
total wait time is 58783ms (avg notify-time per run is 58.783ms)

OK (1 tests)
```

Second test verifies that long tasks and short tasks distributes between threads and we have a garantee that short task don't wait long task if theris a free thread. My realisation returns OK, but this realisation failed

this PR
```shell
time ./Foundation-testrunner testActiveThreadLoadBalancing

testActiveThreadLoadBalancing: FAILURE

!!!FAILURES!!!
Runs: 1   Failures: 1   Errors: 0

There was 1 failure:
 1: CppUnit::TestCaller<ActiveThreadPoolTest>.testActiveThreadLoadBalancing
    "lttPerTIDCount != 0"
    in "/Users/a.bychuk/coding/pet/poco/Foundation/testsuite/src/ActiveThreadPoolTest.cpp", line 130

./Foundation-testrunner testActiveThreadLoadBalancing  0.09s user 0.02s system 0% cpu 12.049 total
```

my PR
```shell
time ./Foundation-testrunner testActiveThreadLoadBalancing

testActiveThreadLoadBalancing:

OK (1 tests)

./Foundation-testrunner testActiveThreadLoadBalancing  0.08s user 0.02s system 0% cpu 21.696 total
```
