### PR TITLE
Poco 1.9.1 version of #2088 - Fix for TCPServerDispatcher race/crash

### LINKED ISSUE #2085: Crash due to race condition in TCPServerDispatcher
#### Expected behavior
Clean server shutdown with no crash.

#### Actual behavior
#0  0x00007fc7d030a0c1 in pthread_kill () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00007fc7c0da4ed1 in ?? () from <signal handler library>.so
#2  <signal handler called>
#3  0x0000000009078380 in ?? ()
#4  0x00007fc7c2ff429f in Poco::PooledThread::run() () from bin/glnxa64/libPocoFoundation.so.48
#5  0x00007fc7c2feff86 in Poco::ThreadImpl::runnableEntry(void*) () from bin/glnxa64/libPocoFoundation.so.48
#6  0x00007fc7d0305064 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#7  0x00007fc7d1ba462d in clone () from /lib/x86_64-linux-gnu/libc.so.6

#### Steps to reproduce the problem
This is a very rare issue that has been causing sporadic crashes in our build and test environment. I believe the issue is reproducible when there is a server.stop() call concurrent with a new socket connection.

I believe the problem is that a new socket connection enqueues the TCPServerDispatcher instance without changing the reference count. That means that if you shutdown the server before the TCPServerDispatcher::run method starts the ref count would go to zero before the AutoPtr in run() has a chance to increment the ref count.

I think that incrementing the ref count before enqueuing TCPServerDispatcher (and decrementing at the end of run()) would resolve the issue and ensure that the run() method can be safely called during server shutdown.

#### POCO version
1.7.9

#### Compiler and version
gcc 6.3.0-GLIBC2.11

#### Operating system and version
debian 8

### PR DESCRIPTION
**Pull request by Burgch**
#2088 was not compatible with the changes missing from 1.9.1 but in develop. This is a 1.9.1 friendly version. Fixes #2085

### CODE REVIEW

File: Net/src/TCPServerDispatcher.cpp [hunk 1]
```diff
@@ -96,7 +96,7 @@ void TCPServerDispatcher::release()
 
 void TCPServerDispatcher::run()
 {
-	AutoPtr<TCPServerDispatcher> guard(this, true); // ensure object stays alive
+	AutoPtr<TCPServerDispatcher> guard(this, false); // ensure _rc is decreased when function exits
```
Comment (aleks-f) [inline Net/src/TCPServerDispatcher.cpp]: false does nothing here, so it can be just `guard(this)`. It would be good to point to the relationship of this with enqueue `++_rc`, since it's a functionality in two distant places

Comment (Burgch) [reply Net/src/TCPServerDispatcher.cpp]: Updated, thanks.
