### PR TITLE
fix #4276: MongoDB::PooledConnection fixed clang warning

### LINKED ISSUE #4276: MongoDB default function deleted clang warning
**Describe the bug**
Compile warning

**To Reproduce**
Seen on CI macOS builds

**Expected behavior**
no warning

**Logs**
```
In file included from src/MongoDBTest.cpp:18:
/Users/runner/work/poco/poco/MongoDB/include/Poco/MongoDB/PoolableConnectionFactory.h:125:20: warning: explicitly defaulted move assignment operator is implicitly deleted [-Wdefaulted-function-deleted]
        PooledConnection& operator=(PooledConnection&&) = default;
                          ^
/Users/runner/work/poco/poco/MongoDB/include/Poco/MongoDB/PoolableConnectionFactory.h:128:49: note: move assignment operator of 'PooledConnection' is implicitly deleted because field '_pool' is of reference type 'Poco::ObjectPool<Connection, Connection::Ptr> &' (aka 'ObjectPool<Poco::MongoDB::Connection, SharedPtr<Poco::MongoDB::Connection>> &')
        Poco::ObjectPool<Connection, Connection::Ptr>& _pool;
                                                     ^
```

**Please add relevant environment information:**
 - macOS 
 - clang

### PR DESCRIPTION
**Pull request by matejk**
PooledConnection now has a pointer to connection pool instead of a reference to make it moveable.

### CODE REVIEW

File: MongoDB/include/Poco/MongoDB/PoolableConnectionFactory.h [hunk 1]
```diff
@@ -125,8 +127,8 @@ class PooledConnection
 	PooledConnection& operator=(PooledConnection&&) = default;
 
 private:
-	Poco::ObjectPool<Connection, Connection::Ptr>& _pool;
-	Connection::Ptr _connection;
+	Poco::ObjectPool<Connection, Connection::Ptr>*	_pool = nullptr;
+	Connection::Ptr 								_connection;
```
Comment (aleks-f) [inline MongoDB/include/Poco/MongoDB/PoolableConnectionFactory.h:131]: few tabs too many seems to have ended up here

**Review by aleks-f — CHANGES_REQUESTED** [review]
